-- AlterTable Session
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "plannedCount" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "difficulty" TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "practicePack" TEXT;

-- AlterTable Question
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "improvedAnswer" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "starSituation" DOUBLE PRECISION;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "starTask" DOUBLE PRECISION;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "starAction" DOUBLE PRECISION;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "starResult" DOUBLE PRECISION;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "fillerWordCount" INTEGER;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "wordCount" INTEGER;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "speakingSeconds" DOUBLE PRECISION;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "wordsPerMinute" DOUBLE PRECISION;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "isFollowUp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "studyTips" TEXT[] DEFAULT ARRAY[]::TEXT[];
